const r=require('express').Router();
const c=require('../controllers/authController');
const {protect}=require('../middleware/authMiddleware');
r.post('/register',c.register);
r.post('/login',c.login);
r.post('/forgot-password',c.forgotPassword);
r.post('/reset-password',c.resetPassword);
r.get('/me',protect,c.me);
r.put('/profile',protect,c.updateProfile);
module.exports=r;
